name = "frenwork"
main = ".svelte-kit/cloudflare/_worker.js"
compatibility_date = "2024-09-14"
compatibility_flags = ["nodejs_compat"]

# Run the Worker closer to external origins (Resend API) to reduce egress latency
[placement]
mode = "smart"

[assets]
directory = ".svelte-kit/cloudflare"
binding = "ASSETS"

# Production environment (default)
[vars]
# Use secrets for production (more secure)
# wrangler secret put TURSO_DATABASE_URL
# wrangler secret put TURSO_AUTH_TOKEN
# wrangler secret put RESEND_API_KEY
# wrangler secret put EMAIL_FROM
# wrangler secret put TURNSTILE_SECRET_KEY

# Development environment
[env.dev]
name = "frenwork-dev"
[env.dev.vars]
# You can put non-sensitive dev variables here
# TURSO_DATABASE_URL = "your-dev-database-url"
# TURSO_AUTH_TOKEN = "your-dev-auth-token"

# Staging environment  
[env.staging]
name = "frenwork-staging"