name = "job-portal"
main = ".svelte-kit/output/server/index.js"
compatibility_date = "2024-09-14"

[site]
bucket = ".svelte-kit/output/client"

# Environment variables will be set in the Cloudflare Workers dashboard
# Add these variables in your Workers settings:
# - TURSO_DATABASE_URL
# - TURSO_AUTH_TOKEN  
# - RESEND_API_KEY
# - EMAIL_FROM